#!/bin/bash

if [[ $# -gt 2 || $# -eq 0 ]]
then
    echo "Usage : finder <flag> <search_term> OR finder <search_term>"
    exit
fi

# Usage: finder "stuff" 
# Will search within all non-binary files
if [[ $# -eq 1 ]]
then
    find . -type f ! -iname '*.html' | xargs grep -E -i -I --color=always -n -C 2 "$1" | less -RM
    exit
fi

# Usage: finder -[f,d,h] "stuff" 
case $1 in
    # Search for file names
    "-f")
		find . -type f -iname "$2" ! -iname '*.html' | less -RM
        ;;
    # Search for directory names
    "-d")
		find . -name "$2" -type d -printf "%p \t%s \t%Ab %Ad, %AY %Al:%AM %Ap\n" | less -RM
        ;;
    # Search among man pages
    "-h")
		find . -type f -iname "*.html" | xargs grep -E -i -I --color=always -n -C 2 "$2" | less -RM
        ;;
    *)
        echo "Incorrect flag! Exiting."
        ;;
esac
